spring:
  profiles:
    active: simple-cache
  main:
    banner-mode: 'off'
  stkdb:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  datasource:
    url: jdbc:h2:mem:test;MVCC=TRUE;
    username: sa
    password:
    driverClassName: org.h2.Driver
    testOnBorrow: true
    validationQuery: select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
    validationInterval: 30000
    maxActive: 100
    maxIdle: 100
    minIdle: 10
    initialSize: 0
    maxWait: 30000
    testOnReturn: false
    testWhileIdle: false
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false
#Tomcat JDBC Enhanced Attributes
    jmxEnabled: true
    fairQueue: true
    abandonWhenPercentageFull: 0
    maxAge: 0
    useEquals: true
    suspectTimeout: 0
    alternateUsernameAllowed: false

logging:
  file: ~/logs
  level:
    ROOT: ERROR
    com.ravi: INFO
server:
  port: 8081

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml