version: '2'
services:
  db:
   image: postgres
   restart: always
   ports:
    - 5432:5432
   volumes:
    - ./pgdata:/var/lib/postgresql/data
   environment:
    - POSTGRES_PASSWORD=stkdb
    - POSTGRES_USER=stkdb
    - TZ=Asia/Kolkata
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080