version: '2'
networks: 
  hisnet:
    driver: bridge
services:
  db:
   image: postgres
   restart: always
   ports:
    - 5432:5432
   volumes:
    - ${PGDATA}:/var/lib/postgresql/data
   environment:
    - POSTGRES_PASSWORD=${PG_PASSWORD}
    - POSTGRES_USER=${PG_USER}
    - TZ=Asia/Kolkata
   networks:
    - hisnet
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
    - hisnet
  bav-loader:
    image: springio/bhav-copy-loader
    restart: always
    volumes:
      - ${BAV_FILE}:/tmp/inbound
    networks:
      - hisnet
    depends_on:
      - db
      - adminer