apiVersion: v1
kind: Service
metadata:
  name: stock-tracker
spec:
  ports:
  - port: 8081
  selector:
    app: stock-tracker
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: stock-tracker
spec:
  selector:
    matchLabels:
      app: stock-tracker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stock-tracker
    spec:
      containers:
      - image: stock-analysis/stock-tracker:latest
        name: stock-tracker
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 8081
